server:
  port: 2333
  address: 0.0.0.0

lavalink:
  server:
    password: "nagham"   # غيّرها لو عا
    sources:
      youtube: true
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      nico: true
      http: true
      local: false
    filters:
      volume: true
      equalizer: true
      karaoke: true
      timescale: true
      tremolo: true
      vibrato: true
      distortion: true
      rotation: true
      channelMix: true
      lowPass: true

metrics:
  prometheus:
    enabled: false

sentry:
  dsn: ""

logging:
  file: ./logs/lavalink.log
  level:
    root: INFO
    lavalink: INFO
